import 'package:project_skillswap/models/allprovidermodel.dart';

final List<Provider> providers = [
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Amal Perera', skill: 'Flutter Development'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Kumari Silva', skill: 'Web Design'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Nimal Fernando', skill: 'Data Science'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Ruwan De Silva', skill: 'Mobile App Development'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Tharushi Jayasinghe', skill: 'Graphic Design'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Sunil Rathnayake', skill: 'Cybersecurity'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Chamari Perera', skill: 'AI and Machine Learning'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Lasantha Gunawardena', skill: 'Software Testing'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Dilrukshi Wijesinghe', skill: 'Project Management'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Prasad Karunaratne', skill: 'Cloud Computing'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Rukshan Wickramasinghe', skill: 'Database Management'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Dulani Samarasinghe', skill: 'UI/UX Design'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Shanika Rajapaksha', skill: 'DevOps'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Mohan Perera', skill: 'Network Administration'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Gayan Alwis', skill: 'SEO Optimization'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Harsha Abeysekera', skill: 'Digital Marketing'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Upul Jayawardene', skill: 'System Analysis'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Kasun Ranatunga', skill: 'Content Writing'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Dilini De Silva', skill: 'E-commerce Development'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Isuru Wijeratne', skill: 'Blockchain Development'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Naduni Bandara', skill: 'Game Development'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Anura Senanayake', skill: 'Big Data Analytics'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Saman Kumara', skill: 'Robotics'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Ayesha Perera', skill: 'Business Analysis'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Lahiru Jayasuriya', skill: 'IT Support'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Nirosha Gamage', skill: 'Video Editing'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Chathura Bandara', skill: 'Social Media Management'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Gayan Perera', skill: 'AR/VR Development'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Amal Perera', skill: 'Painting'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Kumari Silva', skill: 'Plumbing'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Nimal Fernando', skill: 'General Household Activities'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Ruwan De Silva', skill: 'Electrical Work'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Tharushi Jayasinghe', skill: 'Carpentry'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Sunil Rathnayake', skill: 'Masonry'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Chamari Perera', skill: 'Welding'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Lasantha Gunawardena', skill: 'Cleaning Services'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Dilrukshi Wijesinghe', skill: 'Gardening'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Prasad Karunaratne', skill: 'Pest Control'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Rukshan Wickramasinghe', skill: 'Pet Grooming'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Dulani Samarasinghe', skill: 'Catering Services'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Shanika Rajapaksha', skill: 'Handyman Services'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Mohan Perera', skill: 'Furniture Assembly'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Gayan Alwis', skill: 'Window Cleaning'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Harsha Abeysekera', skill: 'Roof Repair'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Upul Jayawardene', skill: 'Landscaping'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Kasun Ranatunga', skill: 'Pool Maintenance'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Dilini De Silva', skill: 'Security System Installation'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Isuru Wijeratne', skill: 'Painting'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Naduni Bandara', skill: 'Plumbing'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Anura Senanayake', skill: 'General Household Activities'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Saman Kumara', skill: 'Electrical Work'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Ayesha Perera', skill: 'Carpentry'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Lahiru Jayasuriya', skill: 'Masonry'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Nirosha Gamage', skill: 'Welding'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Chathura Bandara', skill: 'Cleaning Services'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Gayan Perera', skill: 'Gardening'),
  Provider(profilePhoto: 'images/defaultprofile.jpg', name: 'Ruwanthi Rathnayake', skill: 'Pest Control'),
];
